# Shell variables
# Generated by 'wal'
wallpaper='/home/asuna/Pictures/127524.jpg'

# Special
background='#0a1124'
foreground='#ecc29a'
cursor='#ecc29a'

# Colors
color0='#0a1124'
color1='#63504E'
color2='#A33A4E'
color3='#EB3247'
color4='#F35743'
color5='#F6A73B'
color6='#F9D42E'
color7='#ecc29a'
color8='#a5876b'
color9='#63504E'
color10='#A33A4E'
color11='#EB3247'
color12='#F35743'
color13='#F6A73B'
color14='#F9D42E'
color15='#ecc29a'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
