--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/asuna/Downloads/127524.jpg"

-- Special
background="#0a1124"
foreground="#ecc29a"
cursor="#ecc29a"

-- Colors
color0="#0a1124"
color1="#63504E"
color2="#A33A4E"
color3="#EB3247"
color4="#F35743"
color5="#F6A73B"
color6="#F9D42E"
color7="#ecc29a"
color8="#a5876b"
color9="#63504E"
color10="#A33A4E"
color11="#EB3247"
color12="#F35743"
color13="#F6A73B"
color14="#F9D42E"
color15="#ecc29a"
