Icon = {
   cpu = ' ',
   temp = ' ',
   firefox = '',
   plug = ' ',
   music = ' ',
   mail = '',
   heart = ' ',
   star = ' ',
   signal = ' ',
   power = ' ',
   setting = ' ',
   trash = ' ',
   picture = '',
   edit = '',
   git = ' ',
   launcher = ' ',
   terminal = ' ',
   code = ' ',
   folder_open = ' ',
   github = ' ',
   home = ' ',
   box = ' ',
   reddit = ' ',
   wifi = ' ',
   telegram = ' ',
   user = ' ',
   telegram_circle = ' ',
   moon = ' ',
   sun = ' ',
   calendar = ''
}

return Icon
